### ISSUE TITLE
push value updates to ui

### ISSUE THREAD

**Issue by koryteg** [lifegadget/ui-selectize#8] opened 2015-08-14 19:34 UTC
if I update the `value` param outside of the input box or if there is already a value when the component is loaded the tags do not show up. 

I was going to help with a PR but looks like it is going to take me more than five minutes to figure out what is going on.

**Comment by yankeeinlondon** [comment] 2015-08-14 20:42
@koryteg I'd need you to create a [twiddle](http://ember-twiddle.com/) or some way of demonstrating this as I'm not sure how to reproduce it. If you look at the [online demo](http://development.ui-selectize.divshot.io/) you can see the values do pre-populate. If you open the inspector and manipulate the value outside of the app -- using `set` of course -- you can see the value is updated on the selectize control: [video of demo working](http://www.screencast.com/t/JIPhYiBhOnLy)

**Comment by koryteg** [comment] 2015-08-17 17:15
for some reason it is working now... I think it may have been that the original value that was set on the tags attr of the model was not in the list of tags that to choose from. reason being, I had a tag that was "some_tag" and it got reformatted to "someTag". ?? does that sound correct? also why are you changing the format of tags like that?

**Comment by yankeeinlondon** [comment] 2015-08-17 20:09
it really shouldn't change snake case to camel case ... if you go to the demo and use the last field (which allows creating new fields) try using an underscored tag ... it works. Maybe there is something going on in certain circumstances though. If you can show me a way to reproduce it I can look at it.

In the mean time, I'd like to close this issue if you're ok with that. I'll close it but if you're not happy with that we can reopen.

**Closed as completed by yankeeinlondon** 2015-08-17 20:09 UTC

**Comment by koryteg** [comment] 2015-08-17 20:13
that is fine. you can close. i'll look into this further on my own if I can reproduce Ill reopen with example.

**Comment by validkeys** [comment] 2015-10-19 19:37
I am actually getting this reformatting issue when using dot-syntax. I figured out that if I just pass in an array of values, selectize shows the "label" (the value I see in the dropdown) correctly, but the "value" it is showing in a camelCase. If I instead pass in my data like so:

```
[{value: "dot.syntax"}]
```

and then render the component like so:

```
{{ui-select-imput options=myData valueField="value" labelField="value"}}
```

Then my values and label remain formatted as I had originally intended.
